name: Production (main.yml)

on:
  push:
    branches:
      - main

jobs:

  apply:
    name: Apply shared infrastructure
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: terraform

      - name: Create configuration files and parameters
        shell: bash
        id: config
        env:
          GCP_JSON_CREDENTIALS: ${{ secrets.GCP_JSON_CREDENTIALS }}
          GLOBAL_HCL: ${{ secrets.GLOBAL_HCL }}
        run: |
          echo "$GLOBAL_HCL" > global.hcl
          echo "$GCP_JSON_CREDENTIALS" > gcp_credentials.json

          # Get current branch/tag name
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Apply shared resources infrastructure state
        uses: UpperGit/terraform-action@main
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json

          ENVIRONMENT_ID: ${{ steps.config.outputs.short_ref }}
        with:
          path: terraform/resources